// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3JsD2eaS_U-aQFm9QdsxLRtb7tpXTvI',
    appId: '1:735099133495:android:f1ab1dfe99bdfc1853e9b2',
    messagingSenderId: '735099133495',
    projectId: 'goagrics',
    storageBucket: 'goagrics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEKdIZcPghVScYsPsELkLhdPzBQcNe_A8',
    appId: '1:735099133495:ios:187066fbbd0549e653e9b2',
    messagingSenderId: '735099133495',
    projectId: 'goagrics',
    storageBucket: 'goagrics.appspot.com',
    androidClientId: '735099133495-74feemdgoko857t7t812jufaf2o5qfqh.apps.googleusercontent.com',
    iosClientId: '735099133495-epmaj23623s1ev0uaflhiejjrjdjuma9.apps.googleusercontent.com',
    iosBundleId: 'com.example.goagrics',
  );
}
